export const _ERROR_IN_REDUCER = "ERROR_IN_REDUCER";
export const _DELETE_RESULT = "DELETE_RESULT";

export const _INIT_FRONTEND_STATE = "INIT_FRONTEND_STATE";
export const _SAVE_FRONTEND_STATE = "SAVE_FRONTEND_STATE";

export const _TOGGLE_DARK = "TOGGLE_DARK";
export const _TOGGLE_LEFT_SIDERBAR_MOBILE = "TOGGLE_LEFT_SIDERBAR_MOBILE";
export const _TOGGLE_LEFT_SIDERBAR = "TOGGLE_LEFT_SIDERBAR";
export const _MINIMIZE_LEFT_SIDERBAR = "MINIMIZE_LEFT_SIDERBAR";
export const _CLOSE_LEFT_SIDERBAR = "CLOSE_LEFT_SIDERBAR";

export const _TOGGLE_RIGHT_SIDERBAR = "TOGGLE_RIGHT_SIDERBAR";

export const _LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const _LOGIN_FAILED = "LOGIN_FAILED";

export const _USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const _USER_SIGNUP_FAILED = "USER_SIGNUP_FAILED";

export const _USER_SIGNUP_GOOGLE_SUCCESS = "USER_SIGNUP_GOOGLE_SUCCESS";
export const _USER_SIGNUP_GOOGLE_FAILED = "USER_SIGNUP_GOOGLE_FAILED";

export const _USER_SIGNUP_FACEBOOK_SUCCESS = "USER_SIGNUP_FACEBOOK_SUCCESS";
export const _USER_SIGNUP_FACEBOOK_FAILED = "USER_SIGNUP_FACEBOOK_FAILED";

export const _USER_SIGNUP_INSTAGRAM_SUCCESS = "USER_SIGNUP_INSTAGRAM_SUCCESS";
export const _USER_SIGNUP_INSTAGRAM_FAILED = "USER_SIGNUP_INSTAGRAM_FAILED";

export const _USER_ACTIVATE_SUCCESS = "USER_ACTIVATE_SUCCESS";
export const _USER_ACTIVATE_FAILED = "USER_ACTIVATE_FAILED";

export const _TOKEN_CHECK_SUCCESS = "TOKEN_CHECK_SUCCESS";
export const _TOKEN_CHECK_FAILED = "TOKEN_CHECK_FAILED";

export const _LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const _LOGOUT_FAILED = "LOGOUT_FAILED";

export const _RESET_ACTIVE_USER = "RESET_ACTIVE_USER";

export const _SHOW_MODAL = "SHOW_MODAL";
export const _CLOSE_MODAL = "CLOSE_MODAL";
export const _CLEAR_MODAL = "CLEAR_MODAL";

export const _CHANGE_LANGUAGE = "CHANGE_LANGUAGE";
export const _CHANGE_BACKEND_SERVER = "CHANGE_BACKEND_SERVER";
export const _CHANGE_ACCOUNT = "CHANGE_ACCOUNT";

export const _GET_USER_ACTIONS_SUCCESS = "GET_USER_ACTIONS_SUCCESS";
export const _GET_USER_ACTIONS_FAILED = "GET_USER_ACTIONS_FAILED";
